sonar.projectKey=dotnet-test
sonar.working.directory=/Users/melisa/dotnet-test/.sonarqube/out/.sonar
sonar.projectBaseDir=/Users/melisa/dotnet-test
sonar.pullrequest.cache.basepath=/Users/melisa/dotnet-test

9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.projectKey=dotnet-test:9EB03B23-27E9-570F-7A6A-8192F1D51994
9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.projectName=dotnet-test
9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.projectBaseDir=/Users/melisa/dotnet-test
9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.sourceEncoding=utf-8
9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.tests=
9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.sources=\
"/Users/melisa/dotnet-test/Hesaplama.cs",\
"/Users/melisa/dotnet-test/HesapMakinesi.cs",\
"/Users/melisa/dotnet-test/NotHesaplama.cs",\
"/Users/melisa/dotnet-test/PasscalUcgeni.cs",\
"/Users/melisa/dotnet-test/Program.cs",\
"/Users/melisa/dotnet-test/obj/dotnet-test.csproj.nuget.dgspec.json",\
"/Users/melisa/dotnet-test/obj/project.assets.json",\
"/Users/melisa/dotnet-test/obj/Debug/net10.0/dotnet-test.sourcelink.json",\
"/Users/melisa/dotnet-test/bin/Debug/net10.0/dotnet-test.runtimeconfig.json",\
"/Users/melisa/dotnet-test/bin/Debug/net10.0/dotnet-test.deps.json"

9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.cs.analyzer.projectOutPaths=\
"/Users/melisa/dotnet-test/.sonarqube/out/0"
9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.cs.roslyn.reportFilePaths=\
"/Users/melisa/dotnet-test/.sonarqube/out/0/Issues.json"
9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.cs.scanner.telemetry=\
"/Users/melisa/dotnet-test/.sonarqube/out/0/Telemetry.json"

9EB03B23-27E9-570F-7A6A-8192F1D51994.sonar.working.directory=/Users/melisa/dotnet-test/.sonarqube/out/.sonar/mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=9EB03B23-27E9-570F-7A6A-8192F1D51994

